## Gerando arquivo ARFF

In [50]:
def gravar_arquivo_arff(base_teste, classes):
    tam = len(base_teste[0][0])
    file = open('test.arff','w') 
 
    file.write('@relation teste\n') 
    for i in range(tam):
        file.write('@attribute '+ str(i) +' NUMERIC\n') 
    
    file.write('@attribute classes {')
    
    a = set(classes)
    
    for i in a:
        file.write(str(i)+',')
    
    file.write('}')    
    
    for i in range(tam):
         len(set(classes))
    
    file.write('\n@data\n') 

    for item in base_teste:
        for i in range(len(item[0])):
            file.write("%s," % str(item[0][i])) 
        file.write("%s\n" % item[1])    
 
    file.close() 
    print('arquivo gravado')

In [67]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import os
from statistics import mode

def extrair_caracteristica2(img):
    histB = cv2.calcHist([img],[0],None,[10],[240,250])
    histG = cv2.calcHist([img],[1],None,[10],[240,250])
    histR = cv2.calcHist([img],[2],None,[10],[240,250])
    cv2.normalize(histB, histB)
    cv2.normalize(histG, histG)
    cv2.normalize(histR, histR)
    histFinal = np.append(np.append(histB, histG),histR)
    return histFinal

def extrair_caracteristica(img):
    qtdeVerde = 0
    qtdeAzul = 0
    qtdeVermelho = 0
    qtdeLinhas, qtdeColunas, c = img.shape
    for i in range(qtdeLinhas):
        for j in range(qtdeColunas):
            if(img[i,j,1] > img[i,j,0] and img[i,j,1] > img[i,j,2]):
                qtdeVerde += 1
            if(img[i,j,2] > img[i,j,0] and img[i,j,2] > img[i,j,1]):
                qtdeVermelho += 1    
            if(img[i,j,0] > img[i,j,1] and img[i,j,0] > img[i,j,2]):
                qtdeAzul += 1    
    qtdeVerde2 = qtdeVerde/(qtdeVerde+qtdeAzul+qtdeVermelho)
    qtdeVermelho2 = qtdeVermelho/(qtdeVerde+qtdeAzul+qtdeVermelho)
    qtdeAzul2 = qtdeAzul/(qtdeVerde+qtdeAzul+qtdeVermelho)
    return np.append(np.append(qtdeVerde2, qtdeVermelho2),qtdeAzul2)
    

files_path = [os.path.abspath(x) for x in os.listdir('./') if x.endswith('.jpg')]

base_teste = []
classes = []

#extraindo as características das imagens na base de dados
for i in files_path:
    diretorio, arquivo = os.path.split(i)
    imagem = cv2.imread(arquivo)
    carac = extrair_caracteristica(imagem)
    print(arquivo, carac)
    classe = arquivo.split('-')
    classes.append(classe[0])
    base_teste.append((carac, classe[0]))
    

gravar_arquivo_arff(base_teste, classes)    

1-0.jpg [0.03785566 0.93918671 0.02295763]
1-1.jpg [0.03546014 0.95103124 0.01350862]
1-2.jpg [0.04263125 0.93864643 0.01872233]
2-0.jpg [0.03152892 0.95328619 0.01518488]
2-1.jpg [0.03242571 0.95074003 0.01683426]
2-2.jpg [0.02726544 0.95887272 0.01386184]
3-0.jpg [0.97255575 0.01505622 0.01238803]
3-1.jpg [0.98391621 0.01047316 0.00561062]
3-2.jpg [0.97661491 0.01322599 0.0101591 ]
4-0.jpg [0.06734474 0.90537833 0.02727693]
4-1.jpg [0.05016669 0.91903477 0.03079854]
4-2.jpg [0.06221349 0.90815324 0.02963327]
5-0.jpg [0.06599614 0.91030587 0.02369799]
5-1.jpg [0.06525526 0.91625352 0.01849122]
5-2.jpg [0.06479717 0.9068881  0.02831473]
arquivo gravado


## Agrupamento (clustering) usando o K Means

In [72]:
X = []
for i in base_teste:
    X.append(i[0])

print(X)

[array([0.03785566, 0.93918671, 0.02295763]), array([0.03546014, 0.95103124, 0.01350862]), array([0.04263125, 0.93864643, 0.01872233]), array([0.03152892, 0.95328619, 0.01518488]), array([0.03242571, 0.95074003, 0.01683426]), array([0.02726544, 0.95887272, 0.01386184]), array([0.97255575, 0.01505622, 0.01238803]), array([0.98391621, 0.01047316, 0.00561062]), array([0.97661491, 0.01322599, 0.0101591 ]), array([0.06734474, 0.90537833, 0.02727693]), array([0.05016669, 0.91903477, 0.03079854]), array([0.06221349, 0.90815324, 0.02963327]), array([0.06599614, 0.91030587, 0.02369799]), array([0.06525526, 0.91625352, 0.01849122]), array([0.06479717, 0.9068881 , 0.02831473])]


In [73]:
from sklearn.cluster import KMeans
from sklearn import metrics
import numpy as np
import matplotlib.pyplot as plt

K = 3
kmeans_model = KMeans(n_clusters=K).fit(X)

print(kmeans_model.cluster_centers_)
centers = np.array(kmeans_model.cluster_centers_)

[[0.03452785 0.94862722 0.01684493]
 [0.97769562 0.01291846 0.00938592]
 [0.06262892 0.91100231 0.02636878]]
